### ISSUE TITLE
onCreate not called when hydrating pre-rendered html

### ISSUE THREAD

**Issue by schultek** [agilord/domino#1]
I have some server-rendered html, e.g. `<div></div>`. 

When I first re-render this with domino in order to make it interactive ( `b.open('div', onCreate: (e) {})` ) the `onCreate()` does not get called, since the `div` already exists.

However I need this in order to get hold of the `DomView` instance to update the view on state changes.

So either `onCreate()` is called when it's first seen by domino regardless of it existing before, or I need a different way to get the view after it is created.

**Comment by isoos** [comment]
> However I need this in order to get hold of the DomView instance to update the view on state changes.

can you share (snippet of) the code that tries to do this?

> So either onCreate() is called when it's first seen by domino regardless of it existing before, or I need a different way to get the view after it is created.

`onCreate` as a one-off is a simple abstraction, I wouldn't complicate it with additional parameters. A new `onUpdate`, which gets called all the time may be better, but then, the guarantees are not clear: what if the higher-level rendering method skips the node and doesn't call in directly? I don't mind adding `onUpdate` if that's an acceptable ambiguity there.

**Comment by schultek** [comment]
I think an `onUpdate` would be great.

**Comment by isoos** [comment]
btw. I forgot to mention that https://pub.dev/packages/async_tracker can be used to track async processing (e.g. RPCs, streams, timers) to trigger updating the view. In a prior version this was integrated, but added a bit of confusion, so I've separated it from `domino` core.

**Comment by isoos** [comment]
Fixed in #2 and tested in #3.
