### ISSUE TITLE
DomBuilder.close() should return the created Element

### ISSUE THREAD

**Issue by Blimster** [agilord/domino#4]
Hi, I evaluate to replace Incremental DOM by domino in my package [deact](https://pub.dev/packages/deact).

For my use case, I need a reference to the created [Element](https://api.dart.dev/stable/2.16.1/dart-html/Element-class.html)s. Googles Incremental DOM returns this reference when calling the close() function.

Is it possible to have the same functionality in domino, too?

**Comment by isoos** [comment]
`L? close({String? tag})` could work, but only in the browser context. For the server-side rendering (markup) the builder works directorly into a `StringSink`, which doesn't have the element reference.

Would you be interested writing the PR for it?

**Comment by Blimster** [comment]
Yes, I will give a try.
