### ISSUE TITLE
Named character references support

### ISSUE THREAD

**Issue by Wdestroier** [agilord/domino#9]
Is it possible to use named character references? For example: `&nbsp;`. Would be great to be able to insert raw html anywhere too.
For reference, the HTML standard: https://html.spec.whatwg.org/dev/named-characters.html#named-character-references.

**Comment by isoos** [comment]
@Wdestroier: I see why these would be useful here, but at the same time, I think these should belong in a separate package, as they would be more useful on their own. I'd expect it to be present in a package like `package:html` or it could be a simple package that does this and only this feature.

**Comment by isoos** [comment]
@Wdestroier: I'm revisiting my prior comment because I thought that it was asked on another package of mine (`diacritic`), and the conversion direction is the opposite here. In short, let's zero the previous comment, it is not relevant here.

**Comment by isoos** [comment]
> Is it possible to use named character references? For example: &nbsp;

I think I may have written `&nbsp;` in the past decade a few times, but I haven't seen the need for most of the named character references like `&aacute;` or similar, as every system seem to support unicode and utf-8 nowadays. So writing these characters seems not really worth it.

>  Would be great to be able to insert raw html anywhere too.

The low-level API supports this: https://pub.dev/documentation/domino/latest/domino/DomBuilder/innerHtml.html, although not at any position, only as part of the inner (unsafe) HTML content. If you would write arbitrary HTML as part an attribute, the entire DOM element needs to be written as part of the samie content.

There is no `DomNode` exposure of it, we could add it easily.

However, I don't think I would add more than that, e.g. arbitrary HTML attribute content seems to unsafe and it seems to me that one should always have better safe HTML option. I can see that some apps may need arbitrary inner HTML, hence its support, but if you have compelling evidence for arbitrary attributes, I may reconsider this.

**Comment by Wdestroier** [comment]
> I think I may have written &nbsp; in the past decade a few times, but I haven't seen the need for most of the named character references like &aacute; or similar, as every system seem to support unicode and utf-8 nowadays. So writing these characters seems not really worth it.

True, the main reason I need `&nbsp;` is to rewrite existing code. The "visible" unicode characters are unnecessary to me. I'm unsure if the other whitespace characters, such as `&ensp;` or `&NegativeThickSpace;`, are used. That's why I proposed a general feature.

> The low-level API supports this: https://pub.dev/documentation/domino/latest/domino/DomBuilder/innerHtml.html, although not at any position, only as part of the inner (unsafe) HTML content.

I tried to write `builder.text('Text without'); builder.innerHtml('&nbsp;'); builder.text('CSS styles.');`, but the code threw an exception that the Cursor had been moved.

> I can see that some apps may need arbitrary inner HTML, hence its support.

It's very useful. My workaround to "embed" `&nbsp;` anywhere was to define it as `final nbsp = span(styles: {'white-space': 'pre'}, text: ' ');` and undo a few custom styles applied to the span tag.

**Comment by isoos** [comment]
Have you tried the Unicode escape code for the `&nbsp;`: `\u00a0`? It could be `'Text without\u00a0CSS styles.'`.

**Comment by Wdestroier** [comment]
@isoos Great, `\u00a0` works! Thank you.

> I think I may have written `&nbsp;` in the past decade a few times, but I haven't seen the need for most of the named character references like &aacute; or similar, as every system seem to support unicode and utf-8 nowadays. So writing these characters seems not really worth it.

I agree, I will close this issue as not planned.
